### ISSUE TITLE
Atributo ser usado em duas colunas como chave composta na mesma tabela.

### ISSUE THREAD

**Issue by camila-imagem** [dotnet/EntityFramework.Docs.pt-br#23]
Estou tentando mapear a seguinte situação:
**Tabela A**
Pk_A
... outros atributos

**Tabela B**
Fk_A Fk_A Fk_xpto (Formando a chave composta)
... outros atributos

Consegui ate certa parte, porem uma das FK não é carregada como objeto, aparece apenas com o Id... 

É possível fazer esse tipo de mapeamento?

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 24b2b50e-35f8-9e0b-8ce5-840e1ea816e6
* Version Independent ID: 9e0e6e2c-48fa-76c3-3bd9-813a6df22645
* Content: [Relações-EF Core](https://docs.microsoft.com/pt-br/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
* Content Source: [entity-framework/core/modeling/relationships.md](https://github.com/dotnet/EntityFramework.Docs.pt-br/blob/live/entity-framework/core/modeling/relationships.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @camila-imagem
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @camila-imagem 

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS.

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal.

Verdadeiramente apreciamos sua contribuição para os nossos artigos.

Equipe internacional do Microsoft DOCS
